name: Gettext updates
on:
  push:
    branches: master
jobs:
  gettext_template:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        token: "${{ secrets.GIT_USER_TOKEN }}"
    - uses: elementary/actions/gettext-template@master
      env:
        GIT_USER_TOKEN: "${{ secrets.GIT_USER_TOKEN }}"
        GIT_USER_NAME: "elementaryBot"
        GIT_USER_EMAIL: "builds@elementary.io"
